class ContactSchema extends ItemSchema {
    static FileAs: PropertyDefinition;
    static FileAsMapping: PropertyDefinition;
    static DisplayName: PropertyDefinition;
    static GivenName: PropertyDefinition;
    static Initials: PropertyDefinition;
    static MiddleName: PropertyDefinition;
    static NickName: PropertyDefinition;
    static CompleteName: PropertyDefinition;
    static CompanyName: PropertyDefinition;
    static EmailAddresses: PropertyDefinition;
    static PhysicalAddresses: PropertyDefinition;
    static PhoneNumbers: PropertyDefinition;
    static AssistantName: PropertyDefinition;
    static Birthday: PropertyDefinition;
    static BusinessHomePage: PropertyDefinition;
    static Children: PropertyDefinition;
    static Companies: PropertyDefinition;
    static ContactSource: PropertyDefinition;
    static Department: PropertyDefinition;
    static Generation: PropertyDefinition;
    static ImAddresses: PropertyDefinition;
    static JobTitle: PropertyDefinition;
    static Manager: PropertyDefinition;
    static Mileage: PropertyDefinition;
    static OfficeLocation: PropertyDefinition;
    static PostalAddressIndex: PropertyDefinition;
    static Profession: PropertyDefinition;
    static SpouseName: PropertyDefinition;
    static Surname: PropertyDefinition;
    static WeddingAnniversary: PropertyDefinition;
    static HasPicture: PropertyDefinition;
    static PhoneticFullName: PropertyDefinition;
    static PhoneticFirstName: PropertyDefinition;
    static PhoneticLastName: PropertyDefinition;
    static Alias: PropertyDefinition;
    static Notes: PropertyDefinition;
    static Photo: PropertyDefinition;
    static UserSMIMECertificate: PropertyDefinition;
    static MSExchangeCertificate: PropertyDefinition;
    static DirectoryId: PropertyDefinition;
    static ManagerMailbox: PropertyDefinition;
    static DirectReports: PropertyDefinition;
    static EmailAddress1: IndexedPropertyDefinition;
    static EmailAddress2: IndexedPropertyDefinition;
    static EmailAddress3: IndexedPropertyDefinition;
    static ImAddress1: IndexedPropertyDefinition;
    static ImAddress2: IndexedPropertyDefinition;
    static ImAddress3: IndexedPropertyDefinition;
    static AssistantPhone: IndexedPropertyDefinition;
    static BusinessFax: IndexedPropertyDefinition;
    static BusinessPhone: IndexedPropertyDefinition;
    static BusinessPhone2: IndexedPropertyDefinition;
    static Callback: IndexedPropertyDefinition;
    static CarPhone: IndexedPropertyDefinition;
    static CompanyMainPhone: IndexedPropertyDefinition;
    static HomeFax: IndexedPropertyDefinition;
    static HomePhone: IndexedPropertyDefinition;
    static HomePhone2: IndexedPropertyDefinition;
    static Isdn: IndexedPropertyDefinition;
    static MobilePhone: IndexedPropertyDefinition;
    static OtherFax: IndexedPropertyDefinition;
    static OtherTelephone: IndexedPropertyDefinition;
    static Pager: IndexedPropertyDefinition;
    static PrimaryPhone: IndexedPropertyDefinition;
    static RadioPhone: IndexedPropertyDefinition;
    static Telex: IndexedPropertyDefinition;
    static TtyTddPhone: IndexedPropertyDefinition;
    static BusinessAddressStreet: IndexedPropertyDefinition;
    static BusinessAddressCity: IndexedPropertyDefinition;
    static BusinessAddressState: IndexedPropertyDefinition;
    static BusinessAddressCountryOrRegion: IndexedPropertyDefinition;
    static BusinessAddressPostalCode: IndexedPropertyDefinition;
    static HomeAddressStreet: IndexedPropertyDefinition;
    static HomeAddressCity: IndexedPropertyDefinition;
    static HomeAddressState: IndexedPropertyDefinition;
    static HomeAddressCountryOrRegion: IndexedPropertyDefinition;
    static HomeAddressPostalCode: IndexedPropertyDefinition;
    static OtherAddressStreet: IndexedPropertyDefinition;
    static OtherAddressCity: IndexedPropertyDefinition;
    static OtherAddressState: IndexedPropertyDefinition;
    static OtherAddressCountryOrRegion: IndexedPropertyDefinition;
    static OtherAddressPostalCode: IndexedPropertyDefinition;
    static Instance: ContactSchema;
    RegisterProperties(): any { throw new Error("Not implemented."); }
}

module ContactSchema {
    export module FieldUris {
        export var /* static*/ FileAs: string = "contacts:FileAs";
        export var /* static*/ FileAsMapping: string = "contacts:FileAsMapping";
        export var /* static*/ DisplayName: string = "contacts:DisplayName";
        export var /* static*/ GivenName: string = "contacts:GivenName";
        export var /* static*/ Initials: string = "contacts:Initials";
        export var /* static*/ MiddleName: string = "contacts:MiddleName";
        export var /* static*/ NickName: string = "contacts:Nickname";
        export var /* static*/ CompleteName: string = "contacts:CompleteName";
        export var /* static*/ CompanyName: string = "contacts:CompanyName";
        export var /* static*/ EmailAddress: string = "contacts:EmailAddress";
        export var /* static*/ EmailAddresses: string = "contacts:EmailAddresses";
        export var /* static*/ PhysicalAddresses: string = "contacts:PhysicalAddresses";
        export var /* static*/ PhoneNumber: string = "contacts:PhoneNumber";
        export var /* static*/ PhoneNumbers: string = "contacts:PhoneNumbers";
        export var /* static*/ AssistantName: string = "contacts:AssistantName";
        export var /* static*/ Birthday: string = "contacts:Birthday";
        export var /* static*/ BusinessHomePage: string = "contacts:BusinessHomePage";
        export var /* static*/ Children: string = "contacts:Children";
        export var /* static*/ Companies: string = "contacts:Companies";
        export var /* static*/ ContactSource: string = "contacts:ContactSource";
        export var /* static*/ Department: string = "contacts:Department";
        export var /* static*/ Generation: string = "contacts:Generation";
        export var /* static*/ ImAddress: string = "contacts:ImAddress";
        export var /* static*/ ImAddresses: string = "contacts:ImAddresses";
        export var /* static*/ JobTitle: string = "contacts:JobTitle";
        export var /* static*/ Manager: string = "contacts:Manager";
        export var /* static*/ Mileage: string = "contacts:Mileage";
        export var /* static*/ OfficeLocation: string = "contacts:OfficeLocation";
        export var /* static*/ PhysicalAddressCity: string = "contacts:PhysicalAddress:City";
        export var /* static*/ PhysicalAddressCountryOrRegion: string = "contacts:PhysicalAddress:CountryOrRegion";
        export var /* static*/ PhysicalAddressState: string = "contacts:PhysicalAddress:State";
        export var /* static*/ PhysicalAddressStreet: string = "contacts:PhysicalAddress:Street";
        export var /* static*/ PhysicalAddressPostalCode: string = "contacts:PhysicalAddress:PostalCode";
        export var /* static*/ PostalAddressIndex: string = "contacts:PostalAddressIndex";
        export var /* static*/ Profession: string = "contacts:Profession";
        export var /* static*/ SpouseName: string = "contacts:SpouseName";
        export var /* static*/ Surname: string = "contacts:Surname";
        export var /* static*/ WeddingAnniversary: string = "contacts:WeddingAnniversary";
        export var /* static*/ HasPicture: string = "contacts:HasPicture";
        export var /* static*/ PhoneticFullName: string = "contacts:PhoneticFullName";
        export var /* static*/ PhoneticFirstName: string = "contacts:PhoneticFirstName";
        export var /* static*/ PhoneticLastName: string = "contacts:PhoneticLastName";
        export var /* static*/ Alias: string = "contacts:Alias";
        export var /* static*/ Notes: string = "contacts:Notes";
        export var /* static*/ Photo: string = "contacts:Photo";
        export var /* static*/ UserSMIMECertificate: string = "contacts:UserSMIMECertificate";
        export var /* static*/ MSExchangeCertificate: string = "contacts:MSExchangeCertificate";
        export var /* static*/ DirectoryId: string = "contacts:DirectoryId";
        export var /* static*/ ManagerMailbox: string = "contacts:ManagerMailbox";
        export var /* static*/ DirectReports: string = "contacts:DirectReports";
    }
}

export = ContactSchema;
//module Microsoft.Exchange.WebServices.Data {
//}
//import _export = Microsoft.Exchange.WebServices.Data;
//export = _export;
