// not available in my fork of ews repo.
//AddNewImContactToGroup operation  
//Exchange 2013
//AddImContactToGroup operation  
//Exchange 2013
//AddImGroup operation  
//Exchange 2013
//AddNewTelUriContactToGroup operation  
//Exchange 2013
//AddDistributionGroupToImList operation  
//Exchange 2013
//GetImItemList operation  
//Exchange 2013
//GetImItems operation  
//Exchange 2013
//RemoveContactFromImList operation  
//Exchange 2013
//RemoveImContactFromGroup operation  
//Exchange 2013
//RemoveDistributionGroupFromImList operation  
//Exchange 2013
//RemoveImGroup operation  
//Exchange 2013
//SetImGroup operation  
//Exchange 2013
